# Generated by Django 2.0.7 on 2018-08-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='luminosity',
            field=models.FloatField(null=True),
        ),
    ]
