# Generated by Django 2.0.7 on 2018-09-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sensor_luminosity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='x',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='y',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
