# Generated by Django 2.0.7 on 2018-09-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180912_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='floor',
            field=models.CharField(default='d2', max_length=30),
        ),
    ]
