# Generated by Django 2.0.7 on 2018-11-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_sensor_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='luminosity',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='floor',
            field=models.CharField(default='one', max_length=30),
        ),
    ]
