# Generated by Django 2.0.7 on 2019-03-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190307_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(default='Name', max_length=50),
        ),
    ]
