# Generated by Django 2.0.7 on 2019-03-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sensor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='id',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='serialID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
