# Generated by Django 2.0.7 on 2019-04-08 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190404_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='api.Sensor'),
        ),
    ]
